import {getSettings,setSetting,addActivity} from '../db.js';
import {applyTheme,escapeHTML,pageHead,toast} from '../ui.js';

export async function renderConfiguracoes(root,ctx){
  const s=await getSettings();
  root.innerHTML=`<section class="page">${pageHead('CONFIGURAÇÕES','Personalize a aparência, o perfil e o comportamento geral do sistema.')}
    <form id="settingsForm" class="grid grid-2"><article class="card"><div class="card-head"><h3>Perfil local</h3><span class="badge success">Não publicado</span></div><div class="form-grid"><label class="field span-2"><span>Como deseja ser chamado</span><input name="profileName" maxlength="50" value="${escapeHTML(s.profileName||'VIP')}" required></label><label class="field"><span>Modo inicial</span><select name="currentMode">${['Pessoal','Plantão','Pós-plantão','Folga','Casa','Estudo','Recuperação','Modo mínimo'].map(m=>`<option ${s.currentMode===m?'selected':''}>${m}</option>`).join('')}</select></label><label class="field"><span>Idioma</span><select disabled><option>Português do Brasil</option></select></label></div></article>
    <article class="card"><div class="card-head"><h3>Identidade visual VIP</h3><span class="badge">Metálico</span></div><div class="form-grid"><label class="field"><span>Tema</span><select name="theme"><option value="dark" ${s.theme==='dark'?'selected':''}>Escuro</option><option value="light" ${s.theme==='light'?'selected':''}>Claro</option><option value="system" ${s.theme==='system'?'selected':''}>Automático</option></select></label><label class="field"><span>Tamanho do texto</span><select name="fontScale"><option value="small" ${s.fontScale==='small'?'selected':''}>Compacto</option><option value="normal" ${!s.fontScale||s.fontScale==='normal'?'selected':''}>Normal</option><option value="large" ${s.fontScale==='large'?'selected':''}>Ampliado</option></select></label></div><div class="section-note" style="margin-top:13px">Paleta fixa: azul-marinho, azul elétrico e verde metálico. As cores de alerta permanecem reservadas para risco, atenção e sucesso.</div></article>
    <article class="card span-2"><div class="card-head"><h3>Princípios da versão Genesis</h3><span class="badge success">0.1.0</span></div><div class="grid grid-4"><div class="kv"><small>DADOS</small><strong>Armazenados no navegador</strong></div><div class="kv"><small>INTERNET</small><strong>Não exigida após instalação</strong></div><div class="kv"><small>IA ONLINE</small><strong>Ainda não ativada</strong></div><div class="kv"><small>ATUALIZAÇÃO</small><strong>Arquivos pelo GitHub</strong></div></div><p>A integração com IA será adicionada por uma ponte segura. Nenhuma chave de API deve ser publicada no repositório.</p></article>
    <div class="span-2 action-row"><button class="btn btn-primary" type="submit">Salvar configurações</button><button id="goGuardianBtn" class="btn btn-secondary" type="button">Abrir GUARDIÃO</button></div></form>
  </section>`;
  root.querySelector('#settingsForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget);for(const key of ['profileName','currentMode','theme','fontScale'])await setSetting(key,String(fd.get(key)));await addActivity('configuracao','Preferências atualizadas');applyTheme(Object.fromEntries(fd.entries()));ctx.updateProfile();toast('Configurações salvas.');ctx.refresh();};
  root.querySelector('#goGuardianBtn').onclick=()=>location.hash='#guardiao';
}
